spring.application.name=ModeliaBackend

# Base de datos
spring.datasource.url=jdbc:mariadb://localhost:3306/modelia_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Servidor
server.port=8080

# JWT
jwt.secret=0ccb841f87a2c46ecc843f46eb081b56
jwt.expiration-ms=28800000
jwt.refresh-expiration-ms=7776000000

# Swagger / OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tryItOutEnabled=true

# Servir ficheros .glb estaticos
spring.web.resources.static-locations=file:./modelos3d/,classpath:/static/